# Generated by Django 4.1.2 on 2022-11-09 21:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extesionusuario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='extesionusuario',
            name='red_social',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
