# Generated by Django 4.1.2 on 2022-11-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_extesionusuari2_extesionusuario2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extesionusuario2',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
