# Generated by Django 4.1.2 on 2022-11-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_extesionusuario2_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extesionusuario',
            name='red_social',
        ),
        migrations.AlterField(
            model_name='extesionusuario',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extesionusuario2',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
