# Generated by Django 4.1.2 on 2022-11-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_extesionusuario_red_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extesionusuario2',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='extesionusuario2',
            name='user',
        ),
        migrations.AddField(
            model_name='extesionusuario',
            name='red_social',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
