# Generated by Django 4.1.2 on 2022-11-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_extesionusuario2_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extesionusuario',
            name='red_social',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
