# Generated by Django 4.2.3 on 2023-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_extesionusuario_red_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtesionUsuario2',
        ),
    ]
