# Generated by Django 4.1.1 on 2022-11-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('desarrollador', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('plataformas', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('jugadores', models.IntegerField()),
                ('lanzamiento', models.DateField()),
                ('resumen', models.CharField(max_length=30)),
            ],
        ),
    ]
