# Generated by Django 4.1.3 on 2022-11-12 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
