# Generated by Django 4.1.1 on 2022-11-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videojuegos',
            new_name='Videojuego',
        ),
    ]
