# Generated by Django 4.1.3 on 2022-11-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_videojuego_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='resumen',
            new_name='distribuidor',
        ),
    ]
