# Generated by Django 4.1.1 on 2022-11-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_videojuegos_videojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='precio',
        ),
    ]
