# Generated by Django 4.1.2 on 2022-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_videojuego_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
