# Generated by Django 4.1.3 on 2022-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_resumen_videojuego_distribuidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='caratulas'),
        ),
    ]
