# Generated by Django 4.1.3 on 2022-11-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_videojuego_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='caratula',
        ),
        migrations.CreateModel(
            name='ExtensionVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='caratulas')),
                ('videojuego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
