# Generated by Django 4.1.3 on 2022-11-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_videojuego_caratula_extensionvideojuego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtensionVideojuego',
        ),
    ]
