# Generated by Django 4.1.3 on 2022-11-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_videojuego_fecha_de_creacion'),
        ('games', '0007_videojuego_caratula'),
    ]

    operations = [
    ]
