# Generated by Django 4.1.3 on 2022-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_videojuego_caratula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='caratulas'),
        ),
    ]
